baseurl = "https://masalmon.eu/"
languageCode = "en-us"
title = "Maëlle's R blog"
theme = "blackburn"
author = "Maëlle Salmon"
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 5
rssLimit = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Not a fish"
  brand = "Maëlle"
  googleAnalytics = ""
  disqus = "masalmon"
  # CSS name for highlight.js
  highlightjs = "github"
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "monokai"

  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"
  dateFormat = "2006/01/02"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts by date"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Posts by tag"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 3
    identifier = "tags"
    url = "/tags/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-question-circle fa-fw'></i>"
    weight = 4
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Bio"
    pre = "<i class='fa fa-id-card fa-fw'></i>"
    weight = 5
    identifier = "bio"
    url = "/bio/"
  [[menu.main]]
    name = "Talks"
    pre = "<i class='fa fa-microphone fa-fw'></i>"
    weight = 6
    identifier = "talks"
    url = "/talks/"
  [[menu.main]]
    name = "Scientific papers"
    pre = "<i class='fa fa-file fa-fw'></i>"
    weight = 7
    identifier = "papers"
    url = "/papers/"
  [[menu.main]]
    name = "Privacy policy"
    pre = "<i class='fa fa-user-secret fa-fw'></i>"
    weight = 8
    identifier = "privacy"
    url = "/privacy/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "ma_salmon"
  facebook = ""
  instagram = ""
  github = "maelle"
  stackoverflow = ""
  linkedin = ""
  email = "maelle.salmon@yahoo.se"
  keybase = "maelle_salmon"
  orcid = "0000-0002-2815-0399"
  researchgate = "Maelle_Salmon"

[permalinks]
    post = "/:year/:month/:day/:slug/"